server {
    listen 80;
    listen [::]:80;
    server_name bogatyrevata.com www.bogatyrevata.com;

    root /var/www/bogatyrevata.com/public;
    index index.html;

    access_log /var/log/nginx/bogatyrevata.com-access.log;
    error_log  /var/log/nginx/bogatyrevata.com-error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}