# HTTPS — основной блок
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name bogatyrevata.com www.bogatyrevata.com;

    ssl_certificate     /etc/letsencrypt/live/bogatyrevata.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bogatyrevata.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/bogatyrevata.com/public;
    index index.html;

    access_log /var/log/nginx/bogatyrevata.com-access.log;
    error_log  /var/log/nginx/bogatyrevata.com-error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}

# Редирект HTTP → HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name bogatyrevata.com www.bogatyrevata.com;
    return 301 https://$host$request_uri;
}